symfony:
    container_name: behat_web
    build: docker/web
    volumes:
        - .:/var/www/html
    links:
        - db
        - phantomjs

db:
    image: mysql:5.6
    environment:
        MYSQL_DATABASE: symfony
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./docker/data/mysql:/var/lib/mysql

phantomjs:
    image: cmfatih/phantomjs
    ports:
        - 8643
    entrypoint: phantomjs
    command: "--webdriver=8643"

